### ISSUE TITLE
Remove playground

### ISSUE THREAD

**Issue by ocavue** [remirror/remirror#1079]
### Description

Remove playground since playground is too hard to maintain and we already have Storybook, which is a simpler solution.
 

TODO:

- [x] Remove playground itself from the codebase #1078
- [x] Release a new version of `@remirror/es-module-shims` that add document about deprecation. #1080
- [x] Deprecate `@remirror/es-module-shims` #1083
- [x] Remove the playground code from`remirror` and `@remirror/react`
