### ISSUE TITLE
Release v2

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#1786]
This ticket tracks the open items to create the final v2 release.

### Tasks

- [ ] Create upgrade guide
- [ ] Upgrade 2-3 production apps to v2-beta (to validate upgrade procedure)
- [ ] Remove deprecated features
- [ ] (Optionally) Redo React components
- [ ] Create announcement blog post
