### ISSUE TITLE
Use Playground for live code editor in docs

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#467]
### Description

Currently, when creating a code block in the documentation it can be made editable. In this state it defaults to using docusaurus' `react-live` component.

There are many benefits to using the playground as the editor. It supports both JavaScript and Typescript and allows for more natural editing of the code.

### Tasks

- [ ] Modularise the playground editor into 4 sections: code, display, editable json and a configuration module.
- [ ] Make a live editor using only the code and display sections.
- [ ] Reduce loading times and pre-bundle `@babel/standalone`.
