### ISSUE TITLE
Refactor and simplify `prosemirror-suggest`API

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#548]
### Description

The `prosemirror-suggest` plugin was created a while back to solve a specific need I had at the time; **_creating editable mentions_**. 

It helped me achieve that goal, but it ended up doing too much. My desire to solve every problem imaginable meant that a lot of cruft and unnecessary API's were added to the package. 

To aid adoption, I want to clean up the functionality and drastically reduce the API namespace so that `prosemirror-suggest` does **one** thing and does that **one** thing well.

### Goals

When an activation character is typed, notify me of every change to the following:

- The matching range: `start`, `end` and `cursor` position.
- The matching text: Everything after the activation character that matches the `Suggester`.
- The unique `name` of the `Suggester` which matches: Multiple suggesters can be registered so it's important to be notified of which suggester is currently being called.

Additionally, the API should include the following:

- Only one listener rather than both an `onExit` and `onChange`. All that is needed is the `onChange` which can specify whether the change was an exit.
- Configuration for `invalidNodes`, `invalidMarks` to specify areas of the document where matches should not occur. Conversly, `validNodes`, `validMarks` and also list of nodes adn marks within which a match or 
- Marking a specific range, or match as ignored. At which point the `onChange` handler is no longer activated when entering.

### Tasks

The following tasks help achieve the above goals.

- [x] 💥 Remove the `keyBindings` option and the keyboard handler.
- [x] 💥 Remove `createCommand` handler, since it's up to the developer to interpret the information that's been provided to them. 
- [x] 💥 Remove the `onCharacterPress` keyboard handler.
- [x] 💥 Merge `onExit` functionality into the `onChange` method and split `reason` property into `exitReason` and `changeReason` only one of which can be defined. 
- [x] 🚀 Allow the activation character to be `RegExp`.
- [x] 🚀 Add a `priority` property which allows `suggesters` to specify importance. Higher priority means being checked for a match first.
- [x] 🚀 Support invalid nodes and marks by name.
- [x] 🚀 Support valid nodes and marks by name.
- [x] 🚀 Support an `isValidPosition` handler which is a predicate that is run with the active resolved positioner on each suggester. It allows more advanced criteria for rejecting a `suggester` in the dom.
