### ISSUE TITLE
Add support for asynchronous insertion commands

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#637]
### Description

Prosemirror commands are synchronous. The document can change drastically so that attempting to insert something with a timeout can lead to out of range errors and should be avoided. 

However, there are times when we need to insert content into the document which requires an API response, based on the user input. For example, an image URL may need to be downloaded first before being inserted into the document and a placeholder should be shown while that is happening.

In the time between the API request and the actual solution, it's possible that the content has completely changed and ProseMirror will throw an error if inserting into previous `doc`. 

- Add a configurable placeholder decoration into the document at the position requested
- Configuration options will include the tag to use and possibly the class name.
- When the promise is resolved, it should provide either valid `RemirrorJSON` or a `ProsemirrorNode`.

### Tasks

 

- [ ] Add a command that can take a promise which resolves the attributes and content  to the original position.
- [ ] Use the underlying `@remirror/extension-positioner-tracker` or perhaps deprecate and implement as a `builtin` extension.
- [ ] Allow requests to be [cancellable](https://github.com/sindresorhus/p-cancelable). For example, if the previous position has been removed like if the user selects-all and deletes the whole document.
- [ ] **OPTIONAL**: Explore asynchronous wrapping of content with marks.

### Context

A sponsor has requested this functionality as a priority 💖
