### ISSUE TITLE
Road to `v1`

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#976]
### Description

The following tasks need to be completed for the near term release of `rc.1`.

### Tasks

- [x] Update the dependencies.
- [ ] Use <https://playwright.dev/docs/test-intro> for integration testing.
- [ ] Use <https://github.com/modernweb-dev/web> for all newly added unit tests.
- [x] Setup a discussion with current maintainers.
- [ ] Improve examples in documentation (general documentation improvements).
  - For every stable package there needs to be documentation and that must  be deployed on each release.
  - Examples should move from storybooks to the docs directly.
  - Examples need to be editable in CodeSandbox but rendered directly into the editor as well.
- [x] Update the website design.
- [x] Remove `playground` from docs (temporarily).
- [ ] Move non-stable packages to seperate repositories.
  - [ ] `a11y-status`
  - [ ] `create-context-state`
  - [ ] `jest-prosemirror`
  - [ ] `jest-remirror`
  - [ ] `multishift`
  - [ ] `prosemirror-paste-rules`
  - [ ] `prosemirror-resizable-view`
  - [ ] `prosemirror-suggest`
  - [ ] `prosemirror-trailing-node`
  - [ ] `remirror__cli`
  - [ ] `remirror__es-module-shims`
  - [ ] `remirror__extension-codemirror5`
  - [ ] `remirror__extension-collaboration`
  - [ ] `remirror__extension-diff`
  - [ ] `remirror__extension-epic-mode`
  - [ ] `remirror__extension-react-native-bridge`
  - [ ] `remirror__extension-react-tables`
  - [ ] `remirror__extension-search`
  - [ ] `remirror__i18n`
  - [ ] `remirror__lit`
  - [ ] `remirror__lit-components`
  - [ ] `remirror__messages`
  - [ ] `remirror__playground`
  - [ ] `remirror__react-components`
  - [ ] `remirror__react-debugger`
  - [ ] `remirror__react-editors`
  - [ ] `remirror__react-native`
  - [ ] `remirror__svelte`
  - [ ] `test-keyboard`
- [x] Release the first `rc` version.
